[package]
name = "create-token-metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18.0"
solana-sdk = "1.18.0"
dotenv = "0.15"
serde_json = "1.0"
mpl-token-metadata = "5.1.0"
