[package]
name = "create-token-account"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18.0"
solana-sdk = "1.18.0"
spl-token = "4.0.0"
spl-associated-token-account = "3.0.2"
dotenv = "0.15"
serde_json = "1.0"