[package]
name = "create-token-mint"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18.0"
solana-sdk = "1.18.0"
solana-program = "1.18.0"
spl-token = "3.4.0"
anyhow = "1.0"
dotenv = "0.15"
serde_json = "1.0"