[package]
name = "send-sol"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "1.17"
solana-client = "1.17"
solana-transaction-status = "1.17"
anyhow = "1.0"
dotenv = "0.15"
serde_json = "1.0"
